### ISSUE TITLE
Epic Roadmap to new 2022 conference website

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#101]
@mcturco and @AceTheCreator have decided to take the AsyncAPI 2022 conference website to the next level. This overarching goal here is that we want the website to look astonishing and give an outstanding impression to visitors.

The following is a list of proposed features for the new conference website:
**Target release date**: TBA

- [x] New art direction for the conference 
- [x] Provision of design mockup
- [x] Design implementation
- [ ] Speaker/Attendee card generator
- [ ] Events based attendee notifier for interested sessions(using AsyncAPI)
- [x] Google analytics integration
- [x] Code of Conduct implementation

Kindly let me know if there's something you'd love to add.

CC @derberg @mcturco

**Comment by derberg** [comment]
In regards to Code of Conduct. It is there already, we will just use LF one, like last year, it is mandatory -> https://events.linuxfoundation.org/about/code-of-conduct/

so on the website we need to link to it
