### ISSUE TITLE
[TRACKER] Website maintainace tasks

### ISSUE THREAD

**Issue by ashmit-coder** [asyncapi/conference-website#322]
The following issue is to keep track of the tasks involved in `Conference Website Maintainance Project` 
Ref: #284 

 - [ ] Develop a UI / theme
 - [ ] Implement speaker forms, with Google Forms API
 - [ ] FAQ page
 - [ ] Sponsor prospectus components
 - [ ] Implement testing framework (TBD)
 - [ ] Lighthouse Score Enhancement
 - [ ] Generate testing docs
----
 __Resolved by__:-

**Comment by YashGupt29** [comment]
is there any task which is remaining ?

**Comment by ashmit-coder** [comment]
> is there any task which is remaining ?

Thanks for asking, but there any other tasks, remaining and these issues were under GSoC se they were not open to anyone.
